### PR TITLE
Add Dockerfile + RAxML-NG

### PR DESCRIPTION
**Pull request by niemasd**
Hey, Metin! I'm helping Rob Knight's lab run uDance on their cluster, and as part of that, I wanted to create a Docker container for it.

This PR includes the `Dockerfile` (as well as `.devcontainer` stuff needed to set up the environment automatically in VS Code / GitHub Codespaces).

It also adds `raxml-ng` to the `install.sh` script since RAxML-NG is on bioconda now without any conflicts.

### CODE REVIEW

**Comment by balabanmetin** [comment]
Hi Niema this pull request is very useful, thanks a lot. I will push this as soon as my tests finish. OSX installation (arm chip) is not working due to conda conflicts but it is not because of the changes you made. I am trying to address that now.

**Comment by niemasd** [comment]
No problem; happy to help! Sounds good; no rush

**Comment by balabanmetin** [comment]
`CONDA_SUBDIR=osx-64 conda create -y -c bioconda -c conda-forge --channel smirarab --name udance python pip scipy pandas snakemake`

even the Conda environment described above cannot be created in osx arm64 architecture anymore. I will add a notice to README for the users with Mac arm chip. I will approve these changes. 
I noticed that I introduced a bug in my last commit that prevents using raxml-ng. I will address that right after the merge.

**Comment by balabanmetin** [comment]
the bug is fixed. if you have created a docker image before the fix please redo using the latest version (1.6.5). Did you upload the image somewhere? I can add that to the README.

**Comment by niemasd** [comment]
I have a Docker image here (`niemasd/udance`):

https://hub.docker.com/r/niemasd/udance

It builds from this `Dockerfile`:

https://github.com/Niema-Docker/udance

The existing Docker image was built 4 days ago, so I just kicked off a new build of the Docker image based on your most recent updates (including this merged PR), and it should be ready in ~15 min

**Comment by balabanmetin** [comment]
the dockerfile in Niema-Docker repository is not up-to-date. `rsync` package is missing in that one. The docker file in the pull request has `rsync` package. I tested the image, it works after installing `rsync` via apt. Once you rebuild the Docker image with `rsync` I will add the link to the README.

**Comment by niemasd** [comment]
Woops, thanks for catching that! I just pushed the updated `Dockerfile`, and I just triggered another build. It should be ready in ~20 minutes (same link)

**Comment by balabanmetin** [comment]
OK I added the image link and instructions to the README. Thanks a lot Niema!

**Comment by niemasd** [comment]
No problem 😄

**Pull request merged**
